### PR TITLE
feat(build): add PLACE_VERSION build argument

### PR DESCRIPTION
**Pull request by caspiano**
The `PLACE_VERSION` env var will be accessed via [`PlaceOS::Model::Version`](https://github.com/PlaceOS/models/blob/master/src/placeos-models/version.cr)

### CODE REVIEW

**Comment by kimburgess** [comment]
Couple of related things worth discussing / deciding as part of this PR.

1. Should we move these to `PLACEOS_...` (my vote is yes)
2. Current `PLACE_VERSION` encodes the commit hash from this repository. Should we instead encode the service commit? 
3. It may also be a good idea to concat a date / build ID onto the nightlies.

**Comment by caspiano** [comment]
- `PLACE_COMMIT` should be the commit of the service
- `PLACE_VERSION` should be the current platform version, like `1.2106.0`

I'd rather do the constant rename issue separately. Personally don't see it as much of a big deal

**Comment by kimburgess** [comment]
Ah yes - sorry, that should have been `PLACE_COMMIT` in the comment above. Reason for using the commit from _this_ repo is to help differentiate builds from here vs other sources. Give the version also fills from here too, we should keep these matched.

Keeping the rename seperate to this PR sounds like a good idea though.

**Review by stakach — APPROVED** [review]
LGTM

**Pull request merged**
